import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import localFont from "next/font/local"
import Footer from "./components/Footer";

const fabulous = localFont({
  src: '/static-fonts/fabulous.otf',
  display: 'swap',
})

const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400'], 
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={jost.className}>
        <div className={fabulous.className}>
          <Navbar/>
        </div>
        {children} 
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
